name = "siren"
main = "target/wasm32-unknown-unknown/release/siren.wasm" # <-- DIUBAH: Path output build yang benar
compatibility_date = "2024-05-23"

# Bagian "type = rust" DIHAPUS

[[kv_namespaces]]
binding = "SIREN"
id = "9d05b7b01b374d619d5f8ff372889c3b"

# DITAMBAHKAN KEMBALI dengan perintah modern
[build]
command = "cargo build --target wasm32-unknown-unknown --release"

[vars]
UUID = "7cc46205-67d7-45ca-8a00-619d7320bc14"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/sub.html"
