name = "siren"
main = "src/lib.rs" # <-- Cara modern: Langsung tunjuk ke file Rust utama Anda
compatibility_date = "2024-05-23"
compatibility_flags = ["sockets_connect"] # <-- Flag modern untuk sockets

[[kv_namespaces]]
binding = "SIREN"
id = "9d05b7b01b374d619d5f8ff372889c3b"

[vars]
UUID = "7cc46205-67d7-45ca-8a00-619d7320bc14"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/sub.html"
