name = "siren"
main = "dist/worker.wasm" # <-- DIUBAH: Entrypoint sekarang adalah file .wasm
compatibility_date = "2024-05-23"
type = "rust" # <-- DITAMBAHKAN: Memberitahu wrangler ini proyek Rust

# Minify tidak lagi relevan untuk tipe rust, bisa dihapus atau dibiarkan
minify = true

[[kv_namespaces]]
binding = "SIREN"
id = "9d05b7b01b374d619d5f8ff372889c3b"

# Bagian [build] dan [env.dev] DIHAPUS karena tidak diperlukan lagi
# Wrangler akan melakukan build secara otomatis

[vars]
UUID = "7cc46205-67d7-45ca-8a00-619d7320bc14"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/sub.html"
