name: Deploy Worker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Langkah ini kita tambahkan kembali untuk memastikan
      # cargo dan rustc tersedia untuk wrangler
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      # Sekarang, wrangler-action akan melihat Rust sudah ada
      # dan akan menjalankan build sebelum deploy
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
